### ISSUE TITLE
Looking to extend MFAS on custom dataset

### ISSUE THREAD

**Issue by abhishektyaagi** [slyviacassell/_MFAS#1]
Hi.
Thank you for extending the work on the custom dataset. I am also looking to extend the work on a dataset of my own choice (for object detection tasks). 

Is it possible for you to elaborate a bit on using MFAS framework with our own custom dataset?
I looked at the ModelSearcher class mentioned [here](https://github.com/jperezrua/mfas/blob/master/models/searchable.py).
I understand that there exists one class for each of the datasets.

Now if I want to add my own dataset and want to search for some architectures on it, what do you recommend I should look at as my next step?

**Comment by slyviacassell** [comment]
If you are familiar with Pytorch, I think it is easy to transfer to your costume datasets. You only need to inherit the Dataset class and override the required methods. What's more, I think the searching strategy used in MFAS is quite old. Maybe look the [this literature](https://www.automl.org/automl/literature-on-neural-architecture-search/) for the state-of-the-art method.

**Comment by abhishektyaagi** [comment]
Thank you for your reply.
I will treat your repository as a reference and see what sort of changes I can make for my own custom dataset.

By the way, I am looking at MFAS because I am interested in how they put forward the fusion architecture problem. The link that you shared, I have looked at it but I don't find much literature talking about searching for fusion architectures(multi-modality). Are you aware of any latest work?

**Comment by slyviacassell** [comment]
The MFAS searches the fusion connection paradigm and activation funciton of multi-modality without theoretical explanation, and we are working on it for more reasonable searching.

**Comment by abhishektyaagi** [comment]
I don't think I understand completely what you are referring to.

Is it possible for you to elaborate what you mean by `The MFAS searches the fusion connection paradigm and activation function of multi-modality without theoretical explanation` and `we are working on it for more reasonable searching.`

**Comment by slyviacassell** [comment]
The MFAS was proposed to search how to connect the bi-modal representations and which activation function should be applied to the fused representation. And you could find more technical details on the original paper.

**Comment by abhishektyaagi** [comment]
I appreciate your help. I know we closed the issue, but I was just hoping to know what environment did you use to develop/work on MFAS? (Pytorch, cuda etc versions)

I am just trying to set up my own

**Comment by slyviacassell** [comment]
Pytorch == 1.5.0
CUDA == 10.1
cuDNN == 7

**Comment by abhishektyaagi** [comment]
Thank you!

**Comment by abhishektyaagi** [comment]
Are you aware of what is the correct NTU-Dataset to download for the original MFAS code?
Is it [NTU RGB+D - 3D Skeletons](https://rose1.ntu.edu.sg/dataset/actionRecognition/download) ?

**Comment by slyviacassell** [comment]
Late response. I think the official websites provide enough information for it.
