### ISSUE TITLE
Can’t convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

### ISSUE THREAD

**Issue by abhishektyaagi** [slyviacassell/_MFAS#2]
On [this](https://github.com/slyviacassell/_MFAS/blob/8d582c188bce8fdace83f29cc8b80c9808d823b2/models/search/tools.py#L49) particular line, I am facing the above error

Any idea why that could be the case?

Is it a PyTorch issue? I am using 1.5.0

**Comment by slyviacassell** [comment]
As it is mentioned, you could move the torch.Tensor object from GPU to the host memory with API `Tensor.cpu()`. Anyway, this repository is out of date and there are some bugs that need to fix. Nowadays, I am working on another project, but I am pleasure to fix them in the future.
